import type { Metadata } from "next";
import "../../globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import ReduxProvider from '../../ReduxProvider';
import ThemeRegistry from "../../theme/ThemeRegistry";

export const metadata: Metadata = {
    title: "Notelify | Sign in",
    description: "Generated by create next app",
};

export default function LoginLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReduxProvider>
            <ThemeRegistry>{children}</ThemeRegistry>
        </ReduxProvider>
    );
}